### ISSUE TITLE
Повторяется код чтения данных из консоли

### ISSUE THREAD

**Issue by rimnvd** [rimnvd/lab5#3]
Во всех методах одинаковый цикл:
1. Вывести сообщение
2. Считать строку
3. Преобразовать строку в другой тип
4. Проверить преобразованное значение
5. Если ошибка, то вывести сообщение и повторить цикл

**Comment by AlphaBeth** [comment]
Код мало того, что всё ещё повторяется, так ещё и стал дико сложным. Нужно разбить на отдельные методы по вводу значения каждого поля. Каждый метод может вызывать вспомогательные методы, которые будут производить вывод сообщений, конвертацию данных, проверку данных

**Comment by AlphaBeth** [comment]
Закрыто
